### ISSUE TITLE
No input error for invalid velocity BC type

### ISSUE THREAD

**Issue by tradowsk** [grinsfem/grins#480]
Due to a copy/paste error, I accidentally set the velocity BC to:

         type = 'mole_fractions'
         X_CO2 = '0.001'
         X_N2  = '0.999'

This segfaults in `opt` and gives
`Failed to convert N5GRINS15FEVariablesBaseE reference to N5GRINS28SpeciesMassFractionsVariableE
The N5GRINS15FEVariablesBaseE appears to be a N5GRINS16VelocityVariableE` in `dbg`, neither of which are very helpful in finding the problem.

**Comment by pbauman** [comment]
Agreed that is not as helpful as it could be. Can you give me a stack trace please to help me pin point where to add more useful error messages?

**Comment by tradowsk** [comment]
```
#0  0x000000382e6ac7be in waitpid () from /lib64/libc.so.6
#1  0x000000382e63e5c9 in do_system () from /lib64/libc.so.6
#2  0x00007f75e7983288 in (anonymous namespace)::gdb_backtrace (out_stream=...) at /leela1/data/shared/software/sourcesdir/libmesh/libmesh-master/src/base/print_trace.C:145
#3  0x00007f75e7983615 in libMesh::print_trace (out_stream=...) at /leela1/data/shared/software/sourcesdir/libmesh/libmesh-master/src/base/print_trace.C:192
#4  0x00007f75e797e039 in libMesh::MacroFunctions::report_error (file=0x7f75e93c80f0 "/leela1/data/shared/software/libs/libmesh/master/gcc/6.1.0/mpich/3.2/petsc/3.7.3/openblas/0.2.18/boost/1.61.0/hdf5/1.8.17/vtk/7.1.0/include/libmesh/libmesh_common.h", line=493, date=0x7f75e93c7b2e "Feb 21 2017", time=0x7f75e93c7b25 "13:12:16") at /leela1/data/shared/software/sourcesdir/libmesh/libmesh-master/src/base/libmesh_common.C:82
#5  0x00007f75e90fcb49 in libMesh::cast_ref<GRINS::SpeciesMassFractionsVariable&, GRINS::FEVariablesBase> (oldvar=...) at /leela1/data/shared/software/libs/libmesh/master/gcc/6.1.0/mpich/3.2/petsc/3.7.3/openblas/0.2.18/boost/1.61.0/hdf5/1.8.17/vtk/7.1.0/include/libmesh/libmesh_common.h:493
#6  0x00007f75e90fbd08 in GRINS::GRINSPrivate::VariableWarehouse::get_variable_subclass<GRINS::SpeciesMassFractionsVariable> (var_name=...) at ../../grins_src/src/variables/include/grins/variable_warehouse.h:123
#7  0x00007f75e90f2d1a in GRINS::MoleFractionsDirichletBCFactory::set_vars_to_search_for (this=0x7f75e9742ff8 <GRINS::grins_factory_mole_fractions>, section=..., var_names=..., vars_to_search_for=...) at ../../grins_src/src/boundary_conditions/src/constant_function_dirichlet_bc_factory.C:144
#8  0x00007f75e90f23fc in GRINS::ConstantFunctionDirichletBCFactory::build_func (this=0x7f75e9742ff8 <GRINS::grins_factory_mole_fractions>, input=..., system=..., var_names=..., section=...) at ../../grins_src/src/boundary_conditions/src/constant_function_dirichlet_bc_factory.C:67
#9  0x00007f75e90d9e16 in GRINS::DirichletBCFactoryFunctionBase<libMesh::FunctionBase<double> >::create (this=0x7f75e9742ff8 <GRINS::grins_factory_mole_fractions>) at ../../grins_src/src/boundary_conditions/src/dirichlet_bc_factory_function_base.C:48
#10 0x00007f75e90b36e4 in GRINS::FactoryAbstract<libMesh::DirichletBoundary>::build (name=...) at ../../grins_src/src/common/include/grins/factory_abstract.h:87
#11 0x00007f75e90b1cd3 in GRINS::BCBuilder::construct_dbc_core (this=0x1797490, input=..., system=..., bc_ids=..., fe_var=..., section=..., bc_type=..., dof_map=...) at ../../grins_src/src/boundary_conditions/src/bc_builder.C:101
#12 0x00007f75e90bb7a8 in GRINS::DefaultBCBuilder::build_bcs_by_var_section (this=0x1797490, input=..., system=..., bc_name=..., bc_ids=..., dof_map=..., var_sections=..., bc_id_to_subdomain_id_map=..., neumann_bcs=...) at ../../grins_src/src/boundary_conditions/src/default_bc_builder.C:275
#13 0x00007f75e90ba5dc in GRINS::DefaultBCBuilder::build_bcs (this=0x1797490, input=..., system=..., neumann_bcs=...) at ../../grins_src/src/boundary_conditions/src/default_bc_builder.C:100
#14 0x00007f75e90b1b26 in GRINS::BCBuilder::build_boundary_conditions (input=..., system=..., neumann_bcs=...) at ../../grins_src/src/boundary_conditions/src/bc_builder.C:48
#15 0x00007f75e913af9d in GRINS::MultiphysicsSystem::init_data (this=0x1590b60) at ../../grins_src/src/physics/src/multiphysics_sys.C:137
#16 0x00007f75e81cf531 in libMesh::System::init (this=0x1590b60) at /leela1/data/shared/software/sourcesdir/libmesh/libmesh-master/src/systems/system.C:242
#17 0x00007f75e8191fc3 in libMesh::EquationSystems::init (this=0x15f4080) at /leela1/data/shared/software/sourcesdir/libmesh/libmesh-master/src/systems/equation_systems.C:117
#18 0x00007f75e936350d in GRINS::Solver::initialize (this=0x1592ab0, equation_system=..., system=0x1590b60) at ../../grins_src/src/solver/src/grins_solver.C:81
#19 0x00007f75e936b46c in GRINS::Simulation::init_multiphysics_system (this=0x7ffc85413180, input=...) at ../../grins_src/src/solver/src/simulation.C:165
#20 0x00007f75e936b0b5 in GRINS::Simulation::Simulation (this=0x7ffc85413180, input=..., command_line=..., sim_builder=..., comm=...) at ../../grins_src/src/solver/src/simulation.C:126
#21 0x0000000000420fc7 in main (argc=8, argv=0x7ffc854139b8) at ../../grins_src/src/solver/src/grins.C:109

```
